[General]
network = ClosedQueueingNetB
*.numTandems = 80
parsim-num-partitions = 8  # set it to the same value as numTandems (1 tandem queue per process)
sim-time-limit=150s
**.vector-recording = false
**.scalar-recording= false
**.statistic-recording = false

*.tandemQueue[*].numQueues = 100
*.sDelay = exponential(10s)
*.tandemQueue[*].queue[*].numInitialJobs = 1000
*.tandemQueue[*].queue[*].serviceTime = exponential(0.1s)
*.tandemQueue[*].qDelay = exponential(0.1s)
*.tandemQueue[*].switch[*].retain = 0.9

# assign each tandem queue to a different processor
# (only the first n lines will be used if there are less than 15 tandem queues)
*.tandemQueue[0..10]**.partition-id = 0
*.tandemQueue[10..20]**.partition-id = 1
*.tandemQueue[20..30]**.partition-id = 2
*.tandemQueue[30..40]**.partition-id = 3
*.tandemQueue[40..50]**.partition-id = 4
*.tandemQueue[50..60]**.partition-id = 5
*.tandemQueue[60..70]**.partition-id = 6
*.tandemQueue[70..80]**.partition-id = 7
*.tandemQueue[80..90]**.partition-id = 8


# the following lines are only needed if you want to get exactly the
# same results as in sequential simulation (they ensure a defined order
# of events with the same timestamp)
*.tandemQueue[0..10]**.priority = 0
*.tandemQueue[10..20]**.priority = 1
*.tandemQueue[20..30]**.priority = 2
*.tandemQueue[30..40]**.priority = 3
*.tandemQueue[40..50]**.priority = 4
*.tandemQueue[50..60]**.priority = 5
*.tandemQueue[60..70]**.priority = 6
*.tandemQueue[70..80]**.priority = 7
*.tandemQueue[80..90]**.priority = 8

