import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import glob
import subprocess

'''
    Save the best fitness values at every iteration step as
    a plot for fitness over iteration step.

    hist_values: Historicl values of run metaheuristic
    store_path:  Path to store the plot.
'''


def save_simulation_fitness(hist_values, store_path):

    # Create directory if it doesn't exist
    if not os.path.exists(os.path.dirname(store_path)):
        os.makedirs(os.path.dirname(store_path))
    
    # # From local machine, but I do not really know why anymore. CHECK Notebook if I have
    # # local machine again!
    # # Invert the historical values as the fitness values are the inverse.
    # inverted_values = [1 / x for x in hist_values['fitness']]

    # Extract the 'fitness' values into a list and convert the arrays to regular numbers
    fitness_values = [x for x in hist_values['fitness']]

    # Create the plot
    plt.figure()
    plt.plot(fitness_values, lw=2)
    plt.xlabel('Iteration')
    plt.ylabel('Latency and cost evaluation')
    plt.xlim(0, len(fitness_values) - 1)
    plt.ylim(0, max(fitness_values) + 1)
    plt.xticks(np.arange(0, len(fitness_values), step=1))
    plt.grid()
    plt.savefig("/workspaces/hyper-heuristic-dse-2.0/data/processed/inet_lans.png")


'''
    Read the csv file in path /workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/workflow/results/ab5f71b5e22b1928ce6aeae0ae2aaadb/tictoc.csv to a dataframe. 
    
    Define the dataframe such that it contains all rows with column 'type' having value 'statistic'. Skip on columns 'underflows,overflows,binedges,binvalues'.
'''
def save_hop_count():
    df = pd.read_csv("/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/workflow/results/ab5f71b5e22b1928ce6aeae0ae2aaadb/tictoc.csv")
    df = df[df.type == 'statistic'].drop(columns=['underflows','overflows','binedges','binvalues'])
    
    # For every row, make a box plot with the values 'mean, stddev, min, max'. The plot title should be the value of column 'module'
    for index, row in df.iterrows():
        plt.figure()
        plt.boxplot([row['mean'], row['stddev'], row['min'], row['max']])
        plt.title(f'Hop count distribution - {row["module"]}')
        plt.savefig("/workspaces/hyper-heuristic-dse-2.0/data/processed/" + row['module'] + ".png")

def save_average_response_time():
    # # Specify the directory to add to PATH
    # new_path = '/workspaces/hyper-heuristic-dse-2.0/omnetpp-6.0.1/bin'

    # # Get the current PATH variable
    # current_path = os.environ.get('PATH', '')

    # # Add the new directory to PATH if it's not already present
    # if new_path not in current_path:
    #     os.environ['PATH'] = new_path + os.pathsep + current_path

    # command = "opp_scavetool export -F CSV-R -o x.csv *.sca"
    # directory = r"/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/workflow/results/343ddead4455987aae4c6e56e3cb132a"

    # try:
    #     result = subprocess.run(command, shell=True, cwd=directory, check=True)
    #     print("Command executed successfully.")
    # except subprocess.CalledProcessError as e:
    #     print(f"Error executing the command: {e}")

    # Load the CSV file "x.csv" generated by opp_scavetool
    csv_file_path = "/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/workflow/results/343ddead4455987aae4c6e56e3cb132a/x.csv"

    # Load the CSV file "x.csv" generated by opp_scavetool with specified data types
    df = pd.read_csv(csv_file_path)

    # Filter rows with 'type' column equal to 'statistic' and drop unnecessary columns
    df = df[df['type'] == 'statistic'].drop(columns=['underflows', 'overflows', 'binedges', 'binvalues'])

    # Drop rows with 'NA' values
    df = df.dropna()
    
    # For every row in the filtered DataFrame, create a box plot
    for index, row in df.iterrows():
        plt.figure()
        data = [row['mean'], row['stddev'], row['min'], row['max']]
        plt.boxplot(data)
        plt.title(f'Average response time - {row["run"]}')
        
        # Save the plot as an image with the module name as the filename
        image_path = f"/workspaces/hyper-heuristic-dse-2.0/data/processed/{row['run']}.png"
        plt.savefig(image_path)
        plt.close()  # Close the plot to release resources

    # # Optional: Show or save a summary plot of all the generated box plots
    # # You can adjust the layout and appearance as needed
    # plt.figure()
    # plt.boxplot(df[['mean', 'stddev', 'min', 'max']].values.T)
    # plt.title('Summary of Average response time')
    # plt.xticks(range(1, len(df) + 1), df['run'], rotation=45)
    # plt.savefig("/workspaces/hyper-heuristic-dse-2.0/data/processed/summary.png")
    # plt.close()  # Close the summary plot

    # print("Box plots generated and saved.")


if __name__ == "__main__":
    save_average_response_time()
    # save_hop_count()
    # save_simulation_fitness()
