from tools.logger import logger
from pathlib import Path

import argparse
import os
import shutil
import sys
import pandas as pd
import subprocess
import time

sys.path.append('/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model')
import experiments
from experiments import create_sim_custom_dummy
import experiment_campaign
from src.manager import Manager
from src.utils.config_reader import Config
from src.utils.config_creator import WorkflowConfig


class HeuristicSimulationCoordinator:
    
    def __init__(self, config_path):
        
        # Set up the logger.
        self.logger = logger("coordinator", Path("/workspaces/hyper-heuristic-dse-2.0/data/raw/heuristic_run/logs"))

        # TODO: Change the following hardcoded parameter definition to reading a config file.
        # Define params to set up the Manager.
        experiments_path = "/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/experiments"
        model = "custom"
        num_nodes = 1
        num_workers = 1
        num_sims = 1
        time_stamp = time.strftime("%Y%m%d_%H%M%S")
        
        self.data_path = os.path.join(experiments_path, "data", "campaign_{}".format(model), "n{}_w{}_s{}".format(str(num_nodes), str(num_workers), str(num_sims)), time_stamp)

        sims_path = "/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/sims"
        
        design_queues = [WorkflowConfig.create_design_point_queue_config("base", 0, "FIFO")]
        
        num_threads_per_worker = int(6 / num_workers)
        
        cluster_config = WorkflowConfig.create_local_cluster_config(num_workers, num_threads_per_worker)

        # Define params for configuration file creation.
        workflow_config_file = os.path.join(self.data_path, "config.json")
        workflow_results_folder = os.path.join(self.data_path, "results")
        workflow_logs_folder = os.path.join(self.data_path, "logs")
        workflow_runtime_folder = os.path.join(self.data_path, "runtime")
        
        # Set up workflow configuration file.
        self.logger.info("Setting up workflow configuration file...")
        self.workflow_config = WorkflowConfig(sims_path, "config", "run_sim", "results", "logs", "out",
                            workflow_results_folder, workflow_logs_folder, workflow_runtime_folder, design_queues, "md5-files", cluster_config)
        self.config = self.workflow_config.conf()
        self.workflow_config.write_conf(workflow_config_file)
        
        # Set up the Manager.
        self.logger.info("Setting up the Manager...")
        self.manager = Manager(workflow_config_file, workflow_logs_folder)
        
        # Read the config file.
        self.logger.info("Reading coordinator config file...")
        coordinator_path = "/workspaces/hyper-heuristic-dse-2.0/coordinator"
        coordinator_config_file = "/workspaces/hyper-heuristic-dse-2.0/config/config_coordinator.json"
        self.conf = Config(Path(coordinator_config_file), Path(coordinator_path), "coordinator_config_manager")

    '''
        Shutdown the Manager.
    '''
    def shutdown_manager(self):
        self.manager.shutdown()
    
    '''
        Transform the scalar files generated by the simulation model into a csv format.
    '''
    def transform_scalar_files(self, uid):
        
        # Add the omnetpp bin directory to PATH environment variables.
        self.logger.info("Adding omnetpp bin directory to PATH environment variables")
        new_path = os.path.join(self.conf.tryGet("omnetpp_base"), "bin")
        current_path = os.environ.get('PATH', '')
        if new_path not in current_path:
            os.environ['PATH'] = new_path + os.pathsep + current_path
        
        sim_results_directory = os.path.join(self.data_path, "results", uid)
        # sim_results_directory = os.path.join("/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/workflow", "results", uid)
        scavetool_command = "opp_scavetool export -F CSV-R -o x.csv *.sca"

        # Attempt to transform the scalar files in the given results directory.
        self.logger.info(f"Transforming scalar files to csv in directory: {sim_results_directory}")
        try:
            subprocess.run(scavetool_command, shell=True, cwd=sim_results_directory, check=True)
        except subprocess.CalledProcessError as e:
            self.logger.error(f"Error executing the command: {e}")

        # Remove the scalar files in the given results directory.
        self.logger.info(f"Removing scalar files in directory: {sim_results_directory}")
        for file in os.listdir(sim_results_directory):
            if file.endswith(".sca"):
                os.remove(os.path.join(sim_results_directory, file))
    
    '''
        Collect the simulation stats from the simulation run.

        Args:
            uid: The unique identifier of the simulation run.
    '''
    def obtain_simulation_stats(self, uid):

        # Load the transformed outputted data from the simulation run.

        # # Automated workflow.
        # csv_file_path = os.path.join(self.data_path, "results", uid, "x.csv")
        # Manual operation from running local workflow.
        csv_file_path = os.path.join("/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/workflow", "results", uid, "x.csv")

        df = pd.read_csv(csv_file_path)

        # # Filter rows with 'type' column equal to 'statistic' and drop unnecessary columns
        # df = df[df['type'] == 'statistic'].drop(columns=['underflows', 'overflows', 'binedges', 'binvalues'])
        
        # Get the end-to-end delay statistics that are gathered by default in INET LANS simulation runs.
        df = df[df['type'] == 'histogram']
        df = df[df['module'].str.endswith(".cli")]
        df = df[df['name'].str.startswith("endToEndDelay")]

        # return the average of the column 'mean' in the dataframe.
        return {
            "latency": df['mean'].mean(), 
            "network_cost": 0
        }
    
    '''
        Evaluate the fitness value of the simulation run.

        Args:
            simulation_metrics: The simulation metrics obtained from the simulation run.
    '''
    def fitness_evaluation(self, simulation_metrics):        
        fitness_config = self.conf.tryGet("fitness_config")
        fitness_function = fitness_config["fitness_function"]
        
        # Fitness value evaluates the objectives for latency and network cost.
        if fitness_function == "latency_cost":
            weight_latency = self.conf.tryGet("weight_latency")
            weight_cost = self.conf.tryGet("weight_cost")
            fitness_value = (weight_latency ∗ simulation_metrics["latency"]) + (weight_cost ∗ simulation_metrics["network_cost"])
            return fitness_value
        
        # TODO: Add other fitness functions here.
        else:
            return 0
    
    def simulation_run(self, config_values):
        
        # Set the values of the parameters in the simulation model.
        param_dict = self.set_param_values(config_values)
        
        src_dir = self.conf.tryGet("dummy_sim_src_dir")
        dest_dir = self.conf.tryGet("dummy_sim_dest_dir")
        
        # Duplicate the preferred dummy_sim directory to the custom directory.
        self.duplicate_directory(src_dir, dest_dir, "communicate_intensive.ini")

        # Write an updated version of the ignored param value file from the directory that was just duplicated.
        old_ini_file_path = os.path.join(src_dir, "communicate_intensive.ini")
        new_ini_file_path = os.path.join(dest_dir, "communicate_intensive.ini")
        self.write_new_ini_file(
            old_ini_file_path, 
            new_ini_file_path, 
            param_dict
        )

        # # Define flag values for the experiment campaign.
        # # TODO: Make these configurable.
        # model = "custom"
        # num_nodes = str(1)
        # num_workers = str(1)
        # num_sims = str(1)
        # time_stamp = time.strftime("%Y%m%d_%H%M%S")
        # experiments_path = "/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/experiments"

        # # Run the experiment campaign.
        # uid = self.run_experiment_campaign(model, num_nodes, num_workers, num_sims, time_stamp, experiments_path)

        # Configure siminstances.
        num_sims = self.conf.tryGet("num_sims")
        inet_path = self.conf.tryGet("inet_base")
        dummy_sim_path = self.conf.tryGet("dummy_path")

        print(f"\Creating SIM instance:\n\t{self.config}, \n\t{dummy_sim_path}, \n\t{id}, \n\t{inet_path}\n")

        sim_instances = [create_sim_custom_dummy(self.config, dummy_sim_path, id, inet_path) for id in range(num_sims)]

        print(f"Created SIM instance: {sim_instances}\n")

        # Run the configured simulation model.
        self.manager.enqueue_tasks(sim_instances)
        evaluated_sim_instances = self.manager.evaluate_all()
        uid = evaluated_sim_instances[0].uid

        # Transform the outputted scalar files into csv format.
        self.transform_scalar_files(uid)

        # Collect the simulation stats from the simulation run.
        simulation_metrics = self.obtain_simulation_stats(uid)

        fitness_value = self.fitness_evaluation(simulation_metrics)

        # # Collect the sim_runtime.
        # sim_runtime_csv_file_path = self.campaign_run_collect(model, num_nodes, num_workers, num_sims, time_stamp, experiments_path)
        # sim_exec_time = self.process_simulation_output(sim_runtime_csv_file_path, 'simulation.sim_exec_time')

        return simulation_metrics
    
    @staticmethod
    def process_simulation_output(sim_runtime_csv_file_path, column_name):
        df = pd.read_csv(sim_runtime_csv_file_path)
        sim_exec_time = df.loc[0, column_name]
        return sim_exec_time

    @staticmethod
    def ignore_file(file_name):
        def _ignore(_, filenames):
            return [name for name in filenames if name == file_name]
        return _ignore
    
    @staticmethod
    def write_new_ini_file(old_file_path, new_file_path, param_dict):
        with open(old_file_path, 'r') as old_file, open(new_file_path, 'w') as new_file:
            for line in old_file:
                updated_line = line
                for param, value in param_dict.items():
                    if line.startswith(param):
                        updated_line = f"{param} = {value}\n"
                new_file.write(updated_line)

    @staticmethod
    def update_file_params(filepath, new_params):
        directory, filename = os.path.split(filepath)
        temp_filepath = os.path.join(directory, f"temp_{filename}")
        try:
            with open(filepath, 'r') as file_to_read, open(temp_filepath, 'w') as file_to_write:
                for line in file_to_read:
                    updated_line = line
                    for param, value in new_params.items():
                        if line.startswith(param):
                            updated_line = f"{param} = {value}\n"
                            break
                    file_to_write.write(updated_line)

            # Replace original file with updated file
            shutil.move(temp_filepath, filepath)
        except FileNotFoundError:
            print("File not found.")
        except Exception as e:
            print("An error occurred:", e)

    '''
    Set the values of the parameters in the simulation model.

    Args:
        config_values: A list of values for the parameters in the simulation model.
    '''
    @staticmethod
    def set_param_values(config_values):

        # Boundary configuration.
        boundaries = {
            "*.sDelay": [0.1, 0.5],
            "*.tandemQueue[*].queue[*].serviceTime": [0.1, 0.5],
            "*.tandemQueue[*].qDelay": [0.1, 0.5],
            "*.tandemQueue[*].switch[*].retain": [0.1, 0.5]
        }

        # Dynamic parameters mapped to value distriution.
        param_dict = {
            "*.sDelay": "exponential",
            "*.tandemQueue[*].queue[*].serviceTime": "exponential",
            "*.tandemQueue[*].qDelay": "exponential",
            "*.tandemQueue[*].switch[*].retain": "uniform"
        }

        # Update param_dict based on provided config values following the order of the boundaries.
        for idx, (param_key, _) in enumerate(boundaries.items()):
            distribution = param_dict.get(param_key, None)
            config_value = config_values[idx]  # Fetch the corresponding value from the confiq_values
            
            if distribution == "exponential":
                param_dict[param_key] = f"exponential({config_value}s)"
            elif distribution == "uniform":
                param_dict[param_key] = str(config_value)
            # Add other distributions here...
        
        return param_dict
    
    @staticmethod
    def duplicate_directory(src_dir, dest_dir, file_to_ignore):
        # Delete destination directory if it exists
        if os.path.exists(dest_dir):
            shutil.rmtree(dest_dir)
        # Duplicate a new custom dummy sim directory and ignore the given filename.
        shutil.copytree(src_dir, 
                        dest_dir, 
                        ignore=HeuristicSimulationCoordinator.ignore_file(file_to_ignore)
        )

    @staticmethod
    def run_experiment_campaign(model, num_nodes, num_workers, num_sims, time_stamp, experiments_path):

        # Backup the original command-line arguments
        original_argv = sys.argv
        original_directory = os.getcwd()

        # define flag values for the experiment campaign.
        data_path = os.path.join(experiments_path, "data", "campaign_{}".format(model), "n{}_w{}_s{}".format(num_nodes, num_workers, num_sims), time_stamp)
        
        # Temporarily replace command-line arguments for experiment_campaign.py
        sys.argv = [
            'experiment_campaign.py', 
            '--data_path=' + data_path,
            '--inet_path=/workspaces/omnetpp-6.0.1/inet4.5/', 
            '--sims_path=/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/sims/',
            '--dummy_path=/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/sims/',
            '--platform=local',
            '--model=' + model,
            '--num_nodes=' + num_nodes,
            '--num_workers=' + num_workers,
            '--num_sims=' + num_sims
        ]

        # Temporarily change the working directory
        os.chdir('/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/')

        # Run the main function of the target script
        uid = experiment_campaign.main()

        # Restore original command-line arguments and working directory
        sys.argv = original_argv
        os.chdir(original_directory)

        return uid

    @staticmethod
    def campaign_run_collect(model, num_nodes, num_workers, num_sims, time_stamp, experiments_path):

        # Backup the original command-line arguments
        original_argv = sys.argv
        original_directory = os.getcwd()

        # Temporarily replace command-line arguments for experiments.campaign_run_collect()
        sys.argv = [
            'experiments.py', 
            f'--experiments_path={experiments_path}'
        ]

        # Set up the argument parser for experiments.campaign_run_collect()
        arg_parser = argparse.ArgumentParser()
        arg_parser.add_argument("--experiments_path", default="experiments/", help="specifies the base path of the project")
        args = arg_parser.parse_args()
        results_path = os.path.join(args.experiments_path, "results", "campaign_{}".format(model), "n{}_w{}_s{}".format(num_nodes, num_workers, num_sims), time_stamp)

        # Temporarily change the working directory
        os.chdir('/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/')

        # Run the data collection function of the target script.
        experiments.campaign_run_collect(args, model, num_nodes, num_workers, num_sims, time_stamp)

        # Restore original command-line arguments and working directory
        sys.argv = original_argv
        os.chdir(original_directory)

        return os.path.join(results_path, "sims_runtime.csv")


if __name__ == "__main__":

    coordinator = HeuristicSimulationCoordinator("/workspaces/hyper-heuristic-dse-2.0/config/coordinator.json")

    # # Backup the original command-line arguments
    # original_argv = sys.argv
    # original_directory = os.getcwd()
    
    # # Temporarily replace command-line arguments for experiments.py
    # sys.argv = [
    #     'experiments.py', 
    #     '--experiments_path=/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/experiments/',
    #     '--inet_path=/workspaces/omnetpp-6.0.1/inet4.5/', 
    #     '--sims_path=/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/sims/',
    #     '--dummy_path=/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/sims/',
    #     '--platform=local'
    # ]

    # # Temporarily change the working directory
    # os.chdir('/workspaces/hyper-heuristic-dse-2.0/src/external/simulation_model/')

    # # Run the main function of the target script
    # experiments.main()

    # # Restore original command-line arguments and working directory
    # sys.argv = original_argv
    # os.chdir(original_directory)
